export const currency = [
  { label: "Chinese Yuan", value: "CNY" },
  { label: "U.S. dollar", value: "USD" },
  { label: "Euro", value: "EUR" },
  { label: "Russian Ruble", value: "RUB" },
];

export const commonButtons = [
  { name: "1" },
  { name: "2" },
  { name: "3" },
  { name: "C" },
  { name: "4" },
  { name: "5" },
  { name: "6" },
  { name: "<" },
  { name: "7" },
  { name: "8" },
  { name: "9" },
  { name: "." },
  { name: "00" },
  { name: "0" },
];

export const calculatorButtons = [
  { name: "C" },
  { name: "<" },
  { name: "/" },
  { name: "*" },
  { name: "7" },
  { name: "8" },
  { name: "9" },
  { name: "-" },
  { name: "4" },
  { name: "5" },
  { name: "6" },
  { name: "+" },
  { name: "1" },
  { name: "2" },
  { name: "3" },
  { name: "=" },
  { name: "0" },
  { name: "00" },
  { name: "." },
];
